apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: calc
spec:
  selector:
    matchLabels:
      run: calc-frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: calc-frontend
    spec:
      containers:
      - name: frontend
        image: calc-fe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://localhost:30031

---

apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: calc
spec:
  type: NodePort
  selector:
    run: calc-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30030