apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: calc
data:
  FRONTEND_URL: http://localhost:30030

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: calc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: calc-backend
  template:
    metadata:
      labels:
        run: calc-backend
    spec:
      containers:
      - name: backend
        image: calc-be:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3031
        envFrom:
        - configMapRef:
            name: backend-config

---

apiVersion: v1
kind: Service

metadata:
  name: backend
  namespace: calc
spec:
  type: NodePort
  selector:
    run: calc-backend
  ports:
    - port: 3031
      targetPort: 3031
      nodePort: 30031
